# Generated by Django 5.0.1 on 2024-01-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_account', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profie_picture',
            new_name='profile_picture',
        ),
    ]
