# Generated by Django 5.0.3 on 2024-03-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('category', models.CharField(max_length=30, verbose_name='Category')),
                ('price', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Price')),
                ('itemtype', models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('NONE', 'None of them')], default=None, max_length=8)),
                ('img', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('availables', models.BooleanField(verbose_name=False)),
                ('calorie', models.IntegerField(blank=True)),
            ],
        ),
    ]
