# Generated by Django 5.0.1 on 2024-01-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
